source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'GitHubAuth_Example', :exclusive => true do
  pod "GitHubAuth", :path => "../"
end

target 'GitHubAuth_Tests', :exclusive => true do
  pod "GitHubAuth", :path => "../"

  
end
